# Generated by Django 6.0 on 2025-12-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='track',
            name='tags',
            field=models.ManyToManyField(blank=True, to='music.tag'),
        ),
    ]
