# Generated by Django 6.0 on 2025-12-08 19:09

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_tag_track_cover_track_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='tracks/'),
        ),
    ]
